
GET http://localhost:9999/main/list
Accept: application/json
Authorization: bearer e4976e09-2506-4918-aee3-e1ce9d163ff4

###
GET http://localhost:9999/main/limit?limit=11&page=1
Accept: application/json
Authorization: bearer e4976e09-2506-4918-aee3-e1ce9d163ff4

###
POST http://127.0.0.1:9999/oauth/token?username=张三&password=123456&grant_type=password
Authorization: Basic cGFzc3dvcmQtY2xpZW50OnBhc3N3b3JkLWNsaWVudC0xMjM=

###
POST http://127.0.0.1:9999/oauth/token?grant_type=refresh_token&refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiLlvKDkuIkiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiYXRpIjoiMTU0ZDc5YjctNjE1Ny00MzczLTgxNmUtMTgwMWZmNDAwMzQ1IiwiZXhwIjoxNjI0NTMzMjEyLCJhdXRob3JpdGllcyI6WyJzeXM6dXNlciJdLCJqdGkiOiI0ODQ5MDRjOS04MjRmLTQzMDAtOGRmNC0xMDViZjdiYTcwNDciLCJjbGllbnRfaWQiOiJwYXNzd29yZC1jbGllbnQifQ.fmCa2IkFnlM10DGY6l9NqBjLn17WV5d26BD2dOGeR8ZMoDFRrf2mEvueCw2r2P-Ts9lPmDOeBwbRooGvFFFZ26iP-i7EA3-hmjf8-EwETA67Ceu8nw-gPj5W7U9SiowLZdtSwUqT5AzidpAtcjE_POkVcsbyTJPm-satLwM2JEaAD7i0SJAzBD2lV76_HvgfXqCx_qN8gV8HbwJhPALTLLtOzA9XPjv72XU2AE4pKymv0nBa6y5w52H5w0DK2mfBPbSj4PYyQGmF3F8evmlK-iX_QXM5KVOZljWNQoTp85uIU2RkGI5iVKnr461bHeSVBAzf_uFx7Au2RQ6PTckqxg
Authorization: Basic cGFzc3dvcmQtY2xpZW50OnBhc3N3b3JkLWNsaWVudC0xMjM=

POST http://localhost:9999/main/add
Authorization: bearer e4976e09-2506-4918-aee3-e1ce9d163ff4
Content-Type: application/json

{
  "authorization": "aa:aa",
  "password": "string",
  "type": 1,
  "username": "string"
}
### 调用other服务的方法时
GET http://localhost:9999/oauth/getUserInfo
Accept: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjE5NDMwNTMsInVzZXJfbmFtZSI6IuW8oOS4iSIsImF1dGhvcml0aWVzIjpbInN5czp1c2VyIl0sImp0aSI6IjY2YWVmMWM4LWQ3NjYtNDk5ZC1hZDY0LTQzN2Y3ZjRiYWJkMCIsImNsaWVudF9pZCI6InBhc3N3b3JkLWNsaWVudCIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.cQxcnaoARUfuLrTRKtY24_tRulARq63I8cbqfrQaAa_qliWGJlAu2WaDTagPQgVRP4kuJMaJALnPigTa4SccxeBmCjHe8X6lBhFjMg83AW5Ow0NZZOVTzTwmgL1koHJqNDiBVojYEuvYeO7rAgB9XPgdPA9jcGKA1WmH1mKZRH99DgpYCJaZabkBhYhQfMvbCfamQapdJEwZV3qzoWN9WgqEPEepfvPmY0g9LZgzjAvxuzyvmEuDwDbw47j3LHpCSQpygnKnxbvzMDx1e8A0g9bKmyNO1gV2EHB1y-bdR27k5KYt6eBKxm22XeJ1vJifps4R3bgILtGrvJCwx6Wudw


###
GET http://localhost:9999/oauth/check_token?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiLlvKDkuIkiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiYXRpIjoiYTU4M2FjODItOTlkMC00ODFhLWJlMTUtY2Q2ZWViYmY0MDE4IiwiZXhwIjoxNjI0NTMyNDc0LCJhdXRob3JpdGllcyI6WyJzeXM6dXNlciJdLCJqdGkiOiI5MzU4NWFiYi0wZDAzLTQzYjgtYjY3Ni0zOTNiMDFjYWUxMGQiLCJjbGllbnRfaWQiOiJwYXNzd29yZC1jbGllbnQifQ.G1POaUFF2d2nqqeRYwnzZqHy2A6lhaCqYihw2FsTDXMMxVvM6SYUvgcXM8YtPigpAXk7yXcpDZ-AyseuD3mg8lLlqncAhdKD36eIFH_Hyiy3hCt6l4P2hhkqgwKCP3np6s2zyiWpt6S0JuLPl9l8oePy8Q4AjW5g1-OPTlbDqoSdrL3-DPJlzEV0YKI6C8PU3VNxu1ay_6RTe6DxGkjQ3kGPMvuryWmETjC9oaCoInbTIYeA2yoH1U1yGiuQNt9nH1NWCpaQBjly-J7LmebKYixnvfTrzTATkB4KvNxKwELP5jCqAuqdhfZGNJ3DoNvdiT7wvOeqOLdy7PXC8aGb2A
Accept: application/json


### 调用other服务的方法时
GET http://localhost:8888/other/method
Accept: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjE5NDU0MTQsInVzZXJfbmFtZSI6IuW8oOS4iSIsImF1dGhvcml0aWVzIjpbInN5czp1c2VyIl0sImp0aSI6ImMwMTYwYmY0LTczMzgtNGM5Mi1iOWVjLWNkNzhiYzM4NjkzNyIsImNsaWVudF9pZCI6InBhc3N3b3JkLWNsaWVudCIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.bANwTXFeGOm6yBnKCP920gK7t_H745afO_EBn7wy_CR8AFNb3BbSe4cBxGQcEulIOJkjguKQISp3-XuEU9aa3ju1ydnaMZg0ogTh1YFoDgI-AqZHg7dcIlf3rZ5Srr7m3pq7k2z69RvsA9WFp23SRbWCC6YbBAHex3F6PF5lz7IRlCkVBilIIIzfSJRpnfqv7hhJrpfREHjuaqMdJgDbEB2GNkZHVVYOpsCbO8KgZWwp8t2WbpobzWM3ScrdCB8IHftS_4uJqvRQ5gy6vk-q3UcS5U76g0NH5QWOk82tpAv2p2uqCgHtj1v2D7h-RniA8jg8O_E9A6jGnVPbEk1lSg

###
##授权码模式，在登录，授权之后，返回Code，根据code再去post拿
POST http://127.0.0.1:9999/oauth/token?grant_type=authorization_code&code=r51U41&redirect_uri=https://www.baidu.com


###
GET http://127.0.0.1:9999/oauth/authorize?response_type=code&client_id=code-client&state=sxt&redirect_uri=https://www.baidu.com

